---
resources:
  - ../../../../../global/base/app

nameSuffix: -production

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: base-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: recruitment-tracker-client
      - op: replace
        path: /metadata/annotations/argocd-image-updater.argoproj.io~1image-list
        value: alyas=zen0hub/recruitment_tracker_client
      - op: replace
        path: /spec/project
        value: recruitment-tracker
      - op: replace
        path: /spec/destination/namespace
        value: recruitment-tracker-client
      - op: replace
        path: /spec/source/path
        value: manifest/client/environments/production
