# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: base-svc
spec:
  type: ClusterIP
  ports:
  - name: base-svc
    protocol: TCP
    port: 8000
---
